// ** C1Rqmod Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_RQMOD_H
#define _MZN_CMD_C1_RQMOD_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class C1Rqmod : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Rqmod const & cmd);

public:

    explicit C1Rqmod();
    ~C1Rqmod() = default;

    C1Rqmod(C1Rqmod && rhs) = default;
    C1Rqmod & operator=(C1Rqmod && rhs) = default;
    C1Rqmod(C1Rqmod const & rhs) = default;
    C1Rqmod & operator=(C1Rqmod const & rhs) = default;
    std::string const cmd_name = "c1_rqmod";


    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Rqmod const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_RQMOD_H
