// ** C1Smem Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_C1_SMEM_H
#define _MZN_CMD_C1_SMEM_H

#include "command.h"


#include "cx_mem.h"

#include "command_vector_nb.h"
namespace mzn {

// -------------------------------------------------------------------------- //
class C1Smem : public CommandVectorNb {

friend std::ostream & operator<<(std::ostream & cmd_os, C1Smem const & cmd);

public:

    explicit C1Smem();
    ~C1Smem() = default;

    C1Smem(C1Smem && rhs) = default;
    C1Smem & operator=(C1Smem && rhs) = default;
    std::string const cmd_name = "c1_smem";

    CmdFieldHex<uint32_t> starting_address;
    CmdField<uint16_t> byte_count;
    BmMemoryType memory_type;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;
    // max keys implementation in a separate function/file
    // not part of auto generation
    uint16_t nb(std::vector<uint8_t> const & msg,
                uint16_t mf_begin) const override;
    void create_new_ic(uint8_t const  cmd_key) override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, C1Smem const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_C1_SMEM_H
