// ** CxMem Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_CX_MEM_H
#define _MZN_CMD_CX_MEM_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class CxMem : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, CxMem const & cmd);

public:

    explicit CxMem();
    ~CxMem() = default;

    CxMem(CxMem && rhs) = default;
    CxMem & operator=(CxMem && rhs) = default;
    CxMem(CxMem const & rhs) = default;
    CxMem & operator=(CxMem const & rhs) = default;
    std::string const cmd_name = "cx_mem";

    CmdField<uint16_t> segment_number;
    CmdField<uint16_t> total_number_of_segments;
    CmdFieldVector<0> memory_contents;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, CxMem const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_CX_MEM_H
