// ** CxSmem Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_CX_SMEM_H
#define _MZN_CMD_CX_SMEM_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class CxSmem : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, CxSmem const & cmd);

public:

    explicit CxSmem();
    ~CxSmem() = default;

    CxSmem(CxSmem && rhs) = default;
    CxSmem & operator=(CxSmem && rhs) = default;
    CxSmem(CxSmem const & rhs) = default;
    CxSmem & operator=(CxSmem const & rhs) = default;
    std::string const cmd_name = "cx_smem";

    CmdField<uint16_t> segment_number;
    CmdField<uint16_t> total_number_of_segments;
    CmdFieldVector<0> memory_contents;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, CxSmem const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_CX_SMEM_H
