// ** T1DpWebserver Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_DP_WEBSERVER_H
#define _MZN_CMD_T1_DP_WEBSERVER_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class T1DpWebserver : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, T1DpWebserver const & cmd);

public:

    explicit T1DpWebserver();
    ~T1DpWebserver() = default;

    T1DpWebserver(T1DpWebserver && rhs) = default;
    T1DpWebserver & operator=(T1DpWebserver && rhs) = default;
    T1DpWebserver(T1DpWebserver const & rhs) = default;
    T1DpWebserver & operator=(T1DpWebserver const & rhs) = default;
    std::string const cmd_name = "t1_dp_webserver";

    CmdField<uint16_t> port_number;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1DpWebserver const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_DP_WEBSERVER_H
