// ** T1DpNetserver Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_DP_NETSERVER_H
#define _MZN_CMD_T1_DP_NETSERVER_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class T1DpNetserver : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, T1DpNetserver const & cmd);

public:

    explicit T1DpNetserver();
    ~T1DpNetserver() = default;

    T1DpNetserver(T1DpNetserver && rhs) = default;
    T1DpNetserver & operator=(T1DpNetserver && rhs) = default;
    T1DpNetserver(T1DpNetserver const & rhs) = default;
    T1DpNetserver & operator=(T1DpNetserver const & rhs) = default;
    std::string const cmd_name = "t1_dp_netserver";

    CmdField<uint16_t> port_number;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1DpNetserver const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_DP_NETSERVER_H
