// ** T1FirFilter Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_FIR_FILTER_H
#define _MZN_CMD_T1_FIR_FILTER_H

#include "command.h"


#include "tx_fir_filter.h"

#include "command_vector_nb.h"
namespace mzn {

// -------------------------------------------------------------------------- //
class T1FirFilter : public CommandVectorNb {

friend std::ostream & operator<<(std::ostream & cmd_os, T1FirFilter const & cmd);

public:

    explicit T1FirFilter();
    ~T1FirFilter() = default;

    T1FirFilter(T1FirFilter && rhs) = default;
    T1FirFilter & operator=(T1FirFilter && rhs) = default;
    std::string const cmd_name = "t1_fir_filter";

    CmdField<uint8_t> number_of_bytes;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;
    // max keys implementation in a separate function/file
    // not part of auto generation
    uint16_t nb(std::vector<uint8_t> const & msg,
                uint16_t mf_begin) const override;
    void create_new_ic(uint8_t const  cmd_key) override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1FirFilter const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_FIR_FILTER_H
