// ** T1Ignore Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_IGNORE_H
#define _MZN_CMD_T1_IGNORE_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class T1Ignore : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, T1Ignore const & cmd);

public:

    explicit T1Ignore();
    ~T1Ignore() = default;

    T1Ignore(T1Ignore && rhs) = default;
    T1Ignore & operator=(T1Ignore && rhs) = default;
    T1Ignore(T1Ignore const & rhs) = default;
    T1Ignore & operator=(T1Ignore const & rhs) = default;
    std::string const cmd_name = "t1_ignore";


    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1Ignore const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_IGNORE_H
