// ** T1LogAndTiming Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_LOG_AND_TIMING_H
#define _MZN_CMD_T1_LOG_AND_TIMING_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class T1LogAndTiming : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, T1LogAndTiming const & cmd);

public:

    explicit T1LogAndTiming();
    ~T1LogAndTiming() = default;

    T1LogAndTiming(T1LogAndTiming && rhs) = default;
    T1LogAndTiming & operator=(T1LogAndTiming && rhs) = default;
    T1LogAndTiming(T1LogAndTiming const & rhs) = default;
    T1LogAndTiming & operator=(T1LogAndTiming const & rhs) = default;
    std::string const cmd_name = "t1_log_and_timing";

    CmdFieldArrayChar<2> message_log_seed_location;
    CmdFieldArrayChar<3> message_log_seed_name;
    CmdFieldArrayChar<2> timing_log_seed_location;
    CmdFieldArrayChar<3> timing_log_seed_name;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1LogAndTiming const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_LOG_AND_TIMING_H
