// ** T1MurdockHuttDetector Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_MURDOCK_HUTT_DETECTOR_H
#define _MZN_CMD_T1_MURDOCK_HUTT_DETECTOR_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class T1MurdockHuttDetector : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, T1MurdockHuttDetector const & cmd);

public:

    explicit T1MurdockHuttDetector();
    ~T1MurdockHuttDetector() = default;

    T1MurdockHuttDetector(T1MurdockHuttDetector && rhs) = default;
    T1MurdockHuttDetector & operator=(T1MurdockHuttDetector && rhs) = default;
    T1MurdockHuttDetector(T1MurdockHuttDetector const & rhs) = default;
    T1MurdockHuttDetector & operator=(T1MurdockHuttDetector const & rhs) = default;
    std::string const cmd_name = "t1_murdock_hutt_detector";

    CmdField<uint8_t> number_of_bytes;
    CmdField<uint8_t> detector_number;
    CmdField<uint8_t> detector_filter_number;
    CmdField<uint8_t> iw_parameter;
    CmdField<uint8_t> nht_parameter;
    CmdField<int32_t> filhi_parameter;
    CmdField<int32_t> fillo_parameter;
    CmdField<uint16_t> wa_parameter;
    CmdFieldIgnore<uint16_t> spare_1;
    CmdField<uint16_t> tc_parameter;
    CmdField<uint8_t> x1_parameter_over_2;
    CmdField<uint8_t> x2_parameter_over_2;
    CmdField<uint8_t> x3_parameter_over_2;
    CmdField<uint8_t> xx_parameter;
    CmdField<uint8_t> av_parameter;
    CmdFieldPstring<0> detector_name;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1MurdockHuttDetector const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_MURDOCK_HUTT_DETECTOR_H
