// ** T1ThresholdDetector Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_THRESHOLD_DETECTOR_H
#define _MZN_CMD_T1_THRESHOLD_DETECTOR_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class T1ThresholdDetector : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, T1ThresholdDetector const & cmd);

public:

    explicit T1ThresholdDetector();
    ~T1ThresholdDetector() = default;

    T1ThresholdDetector(T1ThresholdDetector && rhs) = default;
    T1ThresholdDetector & operator=(T1ThresholdDetector && rhs) = default;
    T1ThresholdDetector(T1ThresholdDetector const & rhs) = default;
    T1ThresholdDetector & operator=(T1ThresholdDetector const & rhs) = default;
    std::string const cmd_name = "t1_threshold_detector";

    CmdField<uint8_t> number_of_bytes;
    CmdField<uint8_t> detector_number;
    CmdField<uint8_t> detector_filter_number;
    CmdField<uint8_t> hysterisis_parameter;
    CmdField<uint8_t> window_parameter;
    CmdField<int32_t> high_limit_parameter;
    CmdField<int32_t> low_limit_parameter;
    CmdField<uint16_t> tail_parameter;
    CmdFieldIgnore<uint16_t> spare_1;
    CmdFieldPstring<0> detector_name;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1ThresholdDetector const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_THRESHOLD_DETECTOR_H
