// ** T1VersionNumber Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_VERSION_NUMBER_H
#define _MZN_CMD_T1_VERSION_NUMBER_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class T1VersionNumber : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, T1VersionNumber const & cmd);

public:

    explicit T1VersionNumber();
    ~T1VersionNumber() = default;

    T1VersionNumber(T1VersionNumber && rhs) = default;
    T1VersionNumber & operator=(T1VersionNumber && rhs) = default;
    T1VersionNumber(T1VersionNumber const & rhs) = default;
    T1VersionNumber & operator=(T1VersionNumber const & rhs) = default;
    std::string const cmd_name = "t1_version_number";

    CmdField<uint8_t> version_number;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1VersionNumber const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_VERSION_NUMBER_H
