// ** TxAveragingParameters Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_TX_AVERAGING_PARAMETERS_H
#define _MZN_CMD_TX_AVERAGING_PARAMETERS_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class TxAveragingParameters : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, TxAveragingParameters const & cmd);

public:

    explicit TxAveragingParameters();
    ~TxAveragingParameters() = default;

    TxAveragingParameters(TxAveragingParameters && rhs) = default;
    TxAveragingParameters & operator=(TxAveragingParameters && rhs) = default;
    TxAveragingParameters(TxAveragingParameters const & rhs) = default;
    TxAveragingParameters & operator=(TxAveragingParameters const & rhs) = default;
    std::string const cmd_name = "tx_averaging_parameters";

    CmdField<int32_t> number_of_samples_between_reports;
    CmdField<uint8_t> optional_irr_filter_to_use;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, TxAveragingParameters const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_TX_AVERAGING_PARAMETERS_H
