// ** TxControlDetector Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_TX_CONTROL_DETECTOR_H
#define _MZN_CMD_TX_CONTROL_DETECTOR_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class TxControlDetector : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, TxControlDetector const & cmd);

public:

    explicit TxControlDetector();
    ~TxControlDetector() = default;

    TxControlDetector(TxControlDetector && rhs) = default;
    TxControlDetector & operator=(TxControlDetector && rhs) = default;
    TxControlDetector(TxControlDetector const & rhs) = default;
    TxControlDetector & operator=(TxControlDetector const & rhs) = default;
    std::string const cmd_name = "tx_control_detector";

    CmdField<uint8_t> control_detector_number;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, TxControlDetector const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_TX_CONTROL_DETECTOR_H
