// ** TxCommEvent Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_TX_COMM_EVENT_H
#define _MZN_CMD_TX_COMM_EVENT_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class TxCommEvent : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, TxCommEvent const & cmd);

public:

    explicit TxCommEvent();
    ~TxCommEvent() = default;

    TxCommEvent(TxCommEvent && rhs) = default;
    TxCommEvent & operator=(TxCommEvent && rhs) = default;
    TxCommEvent(TxCommEvent const & rhs) = default;
    TxCommEvent & operator=(TxCommEvent const & rhs) = default;
    std::string const cmd_name = "tx_comm_event";

    CmdField<uint8_t> number;
    CmdFieldPstring<0> name;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, TxCommEvent const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_TX_COMM_EVENT_H
