// ** TxFirMultiplier Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_TX_FIR_MULTIPLIER_H
#define _MZN_CMD_TX_FIR_MULTIPLIER_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class TxFirMultiplier : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, TxFirMultiplier const & cmd);

public:

    explicit TxFirMultiplier();
    ~TxFirMultiplier() = default;

    TxFirMultiplier(TxFirMultiplier && rhs) = default;
    TxFirMultiplier & operator=(TxFirMultiplier && rhs) = default;
    TxFirMultiplier(TxFirMultiplier const & rhs) = default;
    TxFirMultiplier & operator=(TxFirMultiplier const & rhs) = default;
    std::string const cmd_name = "tx_fir_multiplier";

    CmdField<float> fir_multiplier;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, TxFirMultiplier const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_TX_FIR_MULTIPLIER_H
