// ** TxFirFilter Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_TX_FIR_FILTER_H
#define _MZN_CMD_TX_FIR_FILTER_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class TxFirFilter : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, TxFirFilter const & cmd);

public:

    explicit TxFirFilter();
    ~TxFirFilter() = default;

    TxFirFilter(TxFirFilter && rhs) = default;
    TxFirFilter & operator=(TxFirFilter && rhs) = default;
    TxFirFilter(TxFirFilter const & rhs) = default;
    TxFirFilter & operator=(TxFirFilter const & rhs) = default;
    std::string const cmd_name = "tx_fir_filter";

    CmdField<uint8_t> filter_number;
    CmdFieldPstring<0> filter_name;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, TxFirFilter const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_TX_FIR_FILTER_H
