// ** TxGapThreshold Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_TX_GAP_THRESHOLD_H
#define _MZN_CMD_TX_GAP_THRESHOLD_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class TxGapThreshold : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, TxGapThreshold const & cmd);

public:

    explicit TxGapThreshold();
    ~TxGapThreshold() = default;

    TxGapThreshold(TxGapThreshold && rhs) = default;
    TxGapThreshold & operator=(TxGapThreshold && rhs) = default;
    TxGapThreshold(TxGapThreshold const & rhs) = default;
    TxGapThreshold & operator=(TxGapThreshold const & rhs) = default;
    std::string const cmd_name = "tx_gap_threshold";

    CmdField<float> gap_threshold;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, TxGapThreshold const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_TX_GAP_THRESHOLD_H
