// ** TxIrrFilter Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_TX_IRR_FILTER_H
#define _MZN_CMD_TX_IRR_FILTER_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class TxIrrFilter : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, TxIrrFilter const & cmd);

public:

    explicit TxIrrFilter();
    ~TxIrrFilter() = default;

    TxIrrFilter(TxIrrFilter && rhs) = default;
    TxIrrFilter & operator=(TxIrrFilter && rhs) = default;
    TxIrrFilter(TxIrrFilter const & rhs) = default;
    TxIrrFilter & operator=(TxIrrFilter const & rhs) = default;
    std::string const cmd_name = "tx_irr_filter";

    CmdField<float> cutoff_frequency_ratio;
    CmdField<uint8_t> number_of_poles;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, TxIrrFilter const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_TX_IRR_FILTER_H
