// ** TxMaximumFrameCount Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_TX_MAXIMUM_FRAME_COUNT_H
#define _MZN_CMD_TX_MAXIMUM_FRAME_COUNT_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class TxMaximumFrameCount : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, TxMaximumFrameCount const & cmd);

public:

    explicit TxMaximumFrameCount();
    ~TxMaximumFrameCount() = default;

    TxMaximumFrameCount(TxMaximumFrameCount && rhs) = default;
    TxMaximumFrameCount & operator=(TxMaximumFrameCount && rhs) = default;
    TxMaximumFrameCount(TxMaximumFrameCount const & rhs) = default;
    TxMaximumFrameCount & operator=(TxMaximumFrameCount const & rhs) = default;
    std::string const cmd_name = "tx_maximum_frame_count";

    CmdField<uint8_t> maximum_frame_count;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, TxMaximumFrameCount const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_TX_MAXIMUM_FRAME_COUNT_H
