// ** T1ControlDetectorSpecificationBase Class ** //
// Autogenerated in main_create_cmds.cpp from cmds_format.json ** //
// Manzano Software //

#ifndef _MZN_CMD_T1_CONTROL_DETECTOR_SPECIFICATION_BASE_H
#define _MZN_CMD_T1_CONTROL_DETECTOR_SPECIFICATION_BASE_H

#include "command.h"

namespace mzn {

// -------------------------------------------------------------------------- //
class T1ControlDetectorSpecificationBase : public Command {

friend std::ostream & operator<<(std::ostream & cmd_os, T1ControlDetectorSpecificationBase const & cmd);

public:

    explicit T1ControlDetectorSpecificationBase();
    ~T1ControlDetectorSpecificationBase() = default;

    T1ControlDetectorSpecificationBase(T1ControlDetectorSpecificationBase && rhs) = default;
    T1ControlDetectorSpecificationBase & operator=(T1ControlDetectorSpecificationBase && rhs) = default;
    T1ControlDetectorSpecificationBase(T1ControlDetectorSpecificationBase const & rhs) = default;
    T1ControlDetectorSpecificationBase & operator=(T1ControlDetectorSpecificationBase const & rhs) = default;
    std::string const cmd_name = "t1_control_detector_specification_base";

    CmdField<uint8_t> number_of_bytes;
    CmdField<uint8_t> detector_number;
    CmdField<bool> detector_option;
    CmdFieldPstring<0> detector_name;
    CmdFieldVector<0> detector_equation;

    uint16_t msg_to_data(std::vector<uint8_t> const & msg,
                         uint16_t mf_begin) override;

    uint16_t data_to_msg(std::vector<uint8_t> & msg,
                         uint16_t mf_begin) const override;

private:

    std::ostream & os_print(std::ostream & cmd_os) const override;
};


inline std::ostream & operator<<(std::ostream & cmd_os, T1ControlDetectorSpecificationBase const & cmd) {
    return cmd.os_print(cmd_os);
}

} // end namespace
#endif // _MZN_CMD_T1_CONTROL_DETECTOR_SPECIFICATION_BASE_H
