
// ** Bitmap Classes names for testing** //

// Autogenerated in QDP Commands ** //

// Manzano Software //

#ifndef _MZN_TESTING_BITMAPS_
#define _MZN_TESTING_BITMAPS_

#include "gtest/gtest.h"
#include "cmd_field_bitmap.h"

class FixtureCmdFieldBitmaps : public ::testing::Test {
public:
   mzn::BmAdcmodel bm_adcmodel;
   mzn::BmAlerts bm_alerts;
   mzn::BmAuxStatusWebFlags bm_aux_status_web_flags;
   mzn::BmBalerstatus bm_balerstatus;
   mzn::BmBalerstatusSpecial bm_balerstatus_special;
   mzn::BmCalFail bm_cal_fail;
   mzn::BmCalMonitorChannel bm_cal_monitor_channel;
   mzn::BmCalSensorControlBitmap bm_cal_sensor_control_bitmap;
   mzn::BmCalWaveform bm_cal_waveform;
   mzn::BmCalibrationBitmap bm_calibration_bitmap;
   mzn::BmCerr bm_cerr;
   mzn::BmChannelMap bm_channel_map;
   mzn::BmChargingPhase bm_charging_phase;
   mzn::BmConfigurationIdentificationFlags bm_configuration_identification_flags;
   mzn::BmCtrlFlags bm_ctrl_flags;
   mzn::BmDevOpt bm_dev_opt;
   mzn::BmDevUnitid bm_dev_unitid;
   mzn::BmEthernetLinkstatus bm_ethernet_linkstatus;
   mzn::BmFgDataport bm_fg_dataport;
   mzn::BmFgEnvironmental bm_fg_environmental;
   mzn::BmFgFix bm_fg_fix;
   mzn::BmFgSphy bm_fg_sphy;
   mzn::BmFgThread bm_fg_thread;
   mzn::BmFirmwareversion bm_firmwareversion;
   mzn::BmGainPreAmp bm_gain_pre_amp;
   mzn::BmInitialVco bm_initial_vco;
   mzn::BmInputBitmap bm_input_bitmap;
   mzn::BmLinearPhaseFilters bm_linear_phase_filters;
   mzn::BmLoadsOff bm_loads_off;
   mzn::BmMemoryType bm_memory_type;
   mzn::BmMiscInputs bm_misc_inputs;
   mzn::BmPllState bm_pll_state;
   mzn::BmProcessorid bm_processorid;
   mzn::BmRqstat bm_rqstat;
   mzn::BmSdidriver bm_sdidriver;
   mzn::BmSdiphase bm_sdiphase;
   mzn::BmSeedHeaderActivityFlags bm_seed_header_activity_flags;
   mzn::BmSeedHeaderDataQualityFlags bm_seed_header_data_quality_flags;
   mzn::BmSeedHeaderIoAndClockFlags bm_seed_header_io_and_clock_flags;
   mzn::BmSensorControlEnable bm_sensor_control_enable;
   mzn::BmSensorControlOutput bm_sensor_control_output;
   mzn::BmSerialsensorUnits bm_serialsensor_units;
   mzn::BmSerialsensorValidfields bm_serialsensor_validfields;
   mzn::BmStatCalibratorStatus bm_stat_calibrator_status;
   mzn::BmStatClockQuality bm_stat_clock_quality;
   mzn::BmStatStatusBitmap bm_stat_status_bitmap;

    virtual void SetUp() {

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        

        
   }
};
#endif